/**
 * Assembles the Express app: body parsing, global middleware, the endpoint routers, a
 * terminal 404, and the error handler last.
 *
 * TWO DELIBERATE OMISSIONS versus conduit's `ConduitService`:
 *
 * 1. NO `cors()`. FreeMail answers CORS with managed API Gateway CORS, configured in
 *    `ApiConstruct`. That is not a preference: an authorizer DENY is generated by API
 *    Gateway BEFORE the integration runs, so a Lambda-side helper could never attach
 *    `Access-Control-Allow-Origin` to it — and the SPA's transparent-refresh flow depends
 *    on being able to READ that 403 to know its access cookie expired. A `cors()` here
 *    would cover only the requests that already reach Express, i.e. the ones that least
 *    need it, while duplicating a policy that lives in the CDK.
 *
 * 2. NO `express.urlencoded()`. FreeMail is JSON-only, and accepting form-encoded bodies
 *    would directly undermine #47 Layer 3: `application/x-www-form-urlencoded` is exactly
 *    the "simple request" shape a cross-site `<form>` POST can send WITHOUT a preflight.
 *    The gate rejects that content type; parsing it would be building the door we just
 *    locked.
 */
import express from 'express';
import type { ErrorRequestHandler, Express, RequestHandler } from 'express';
import type { Endpoints } from '../routes/endpoints.js';

/**
 * API Gateway HTTP APIs cap a request payload at 10 MB, so accepting more here could only
 * ever fail later. Send requests carry base64 attachments (7 MB of attachment inflates to
 * ~9.3 MB encoded), which is why this is not conduit's 100 kb.
 */
const JSON_BODY_LIMIT = '10mb';

export interface FreeMailServiceProps {
  /** Global middleware, applied in order before any route. */
  readonly middleware: readonly RequestHandler[];
  readonly endpoints: readonly Endpoints[];
  readonly notFoundHandler: RequestHandler;
  readonly errorHandler: ErrorRequestHandler;
}

export class FreeMailService {
  private readonly app: Express;
  private readonly middleware: readonly RequestHandler[];
  private readonly endpoints: readonly Endpoints[];
  private readonly notFoundHandler: RequestHandler;
  private readonly errorHandler: ErrorRequestHandler;

  constructor(props: FreeMailServiceProps) {
    this.app = express();
    this.middleware = props.middleware;
    this.endpoints = props.endpoints;
    this.notFoundHandler = props.notFoundHandler;
    this.errorHandler = props.errorHandler;
  }

  init(): Express {
    // Nothing should advertise the framework to a caller.
    this.app.disable('x-powered-by');
    this.app.use(express.json({ limit: JSON_BODY_LIMIT }));
    for (const mw of this.middleware) {
      this.app.use(mw);
    }
    for (const ep of this.endpoints) {
      ep.bind(this.app);
    }
    this.app.use(this.notFoundHandler);
    this.app.use(this.errorHandler);
    return this.app;
  }
}
